// Auto-generated by scripts/generate-sidebar.ts
// Do not edit manually - run 'npm run gen:sidebar' to regenerate

import type { DefaultTheme } from 'vitepress'

export const sidebar2026: DefaultTheme.SidebarItem[] = [
  {
    text: 'Overview',
    link: '/2026/',
  },
  {
    text: 'February',
    collapsed: false,
    items: [
      {
        text: '2026-02-23',
        collapsed: true,
        items: [
          {
            text: 'Overview',
            link: '/2026/02/23/',
          },
          {
            text: 'Claude Code Glm',
            link: '/2026/02/23/claude-code-glm',
          },
          {
            text: 'Tested',
            link: '/2026/02/23/tested',
          },
          {
            text: 'Uv Install',
            link: '/2026/02/23/uv-install',
          },
          {
            text: 'X Api Skills',
            link: '/2026/02/23/x-api-skills',
          },
          {
            text: 'X Community',
            link: '/2026/02/23/x-community',
          },
          {
            text: 'X Oauth2',
            link: '/2026/02/23/x-oauth2',
          }
        ]
      },
      {
        text: '2026-02-24',
        collapsed: true,
        items: [
          {
            text: 'Overview',
            link: '/2026/02/24/',
          },
          {
            text: 'Github Pages',
            link: '/2026/02/24/github-pages',
          },
          {
            text: 'Restructure',
            link: '/2026/02/24/restructure',
          },
          {
            text: 'Security',
            link: '/2026/02/24/security',
          },
          {
            text: 'Task Management',
            link: '/2026/02/24/task-management',
          },
          {
            text: 'Vitepress Setup',
            link: '/2026/02/24/vitepress-setup',
          }
        ]
      },
      {
        text: '2026-02-25',
        collapsed: true,
        items: [
          {
            text: 'Overview',
            link: '/2026/02/25/',
          },
          {
            text: 'Background Image',
            link: '/2026/02/25/background-image',
          },
          {
            text: 'Documentation',
            link: '/2026/02/25/documentation',
          },
          {
            text: 'Idea Dev Skill',
            link: '/2026/02/25/idea-dev-skill',
          },
          {
            text: 'Idea Proposal System',
            link: '/2026/02/25/idea-proposal-system',
          },
          {
            text: 'Kimi Cli',
            link: '/2026/02/25/kimi-cli',
          },
          {
            text: 'Nested Sub Agents Experiment',
            link: '/2026/02/25/nested-sub-agents-experiment',
          },
          {
            text: 'Openclaw Skills',
            link: '/2026/02/25/openclaw-skills',
          },
          {
            text: 'Test',
            link: '/2026/02/25/test',
          },
          {
            text: 'Theme Customization',
            link: '/2026/02/25/theme-customization',
          },
          {
            text: 'X Filtered Stream',
            link: '/2026/02/25/x-filtered-stream',
          },
          {
            text: 'X Read Skill',
            link: '/2026/02/25/x-read-skill',
          }
        ]
      },
      {
        text: '2026-02-26',
        collapsed: true,
        items: [
          {
            text: 'Overview',
            link: '/2026/02/26/',
          },
          {
            text: 'Idea Dev',
            link: '/2026/02/26/idea-dev',
          },
          {
            text: 'Kimi Code Cli',
            link: '/2026/02/26/kimi-code-cli',
          },
          {
            text: 'Tinyclaw',
            link: '/2026/02/26/tinyclaw',
          },
          {
            text: 'Topic',
            link: '/2026/02/26/topic',
          },
          {
            text: 'Webhook',
            link: '/2026/02/26/webhook',
          },
          {
            text: 'X',
            link: '/2026/02/26/x',
          },
          {
            text: 'X Filtered Stream Discord Webhook',
            link: '/2026/02/26/x-filtered-stream-discord-webhook',
          }
        ]
      },
      {
        text: '2026-02-28',
        collapsed: true,
        items: [
          {
            text: 'Overview',
            link: '/2026/02/28/',
          },
          {
            text: 'Github Project',
            link: '/2026/02/28/github-project',
          },
          {
            text: 'Nano Banana 2',
            link: '/2026/02/28/nano-banana-2',
          },
          {
            text: 'Notification History',
            link: '/2026/02/28/notification-history',
          },
          {
            text: 'Openclaw Secrets',
            link: '/2026/02/28/openclaw-secrets',
          },
          {
            text: 'Secret Scan Recommendation',
            link: '/2026/02/28/secret-scan-recommendation',
          },
          {
            text: 'Secretary Bot',
            link: '/2026/02/28/secretary-bot',
          },
          {
            text: 'Task Cron',
            link: '/2026/02/28/task-cron',
          },
          {
            text: 'Task Migration',
            link: '/2026/02/28/task-migration',
          },
          {
            text: 'Tweet',
            link: '/2026/02/28/tweet',
          }
        ]
      }
    ]
  },
  {
    text: 'March',
    collapsed: false,
    items: [
      {
        text: '2026-03-01',
        collapsed: true,
        items: [
          {
            text: 'Overview',
            link: '/2026/03/01/',
          },
          {
            text: 'Github Project',
            link: '/2026/03/01/github-project',
          },
          {
            text: 'Secretary Bot Enhancement',
            link: '/2026/03/01/secretary-bot-enhancement',
          }
        ]
      },
      {
        text: '2026-03-02',
        collapsed: true,
        items: [
          {
            text: 'Overview',
            link: '/2026/03/02/',
          },
          {
            text: 'Secretary Bot S6',
            link: '/2026/03/02/secretary-bot-s6',
          },
          {
            text: 'Topic',
            link: '/2026/03/02/topic',
          },
          {
            text: 'Vision',
            link: '/2026/03/02/vision',
          },
          {
            text: 'Vision Changes',
            link: '/2026/03/02/vision-changes',
          }
        ]
      },
      {
        text: '2026-03-03',
        collapsed: true,
        items: [
          {
            text: 'Overview',
            link: '/2026/03/03/',
          },
          {
            text: 'Star Office Ui Guide',
            link: '/2026/03/03/star-office-ui-guide',
          }
        ]
      }
    ]
  }
]

export const sidebarPapers: DefaultTheme.SidebarItem[] = [
  {
    text: '📚 Papers Library',
    link: '/papers/',
  },
  {
    text: 'Categories',
    collapsed: false,
    items: [
      {
        text: '🤖 LLM',
        link: '/papers/category/llm/',
      },
      {
        text: '👁️ Vision',
        link: '/papers/category/vision/',
      },
      {
        text: '🧠 Reasoning',
        link: '/papers/category/reasoning/',
      },
      {
        text: '🤖 Agents',
        link: '/papers/category/agents/',
      },
      {
        text: '⚡ Training',
        link: '/papers/category/training/',
      }
    ]
  }
]

export const sidebar: DefaultTheme.Sidebar = {
  '/2026/': [{ text: '2026', items: sidebar2026 }],
  '/architecture/': [{ text: 'アーキテクチャ', items: [{ text: 'Overview', link: '/architecture/' }] }],
  '/papers/': [{ text: '📚 AGI Papers', items: sidebarPapers }]
}
